# overwrite config from common configs
logging:
  level:
    root: DEBUG

#elastic-query-web-client:
#  webclient:
#    instances:
#      -
#        id: elastic-query-service-1
#        host: localhost
#        port: 8183